name: Build and deploy ASP.Net Core app to Azure Web App - bucstop

on:
  push:
    branches:
      - prod
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build with dotnet
        working-directory: BucStop_Webapp/BucStop
        run: dotnet build --configuration Release

      - name: dotnet publish
        working-directory: BucStop_Webapp/BucStop
        run: dotnet publish -c Release -o ${{ github.workspace }}/publish_output

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{ github.workspace }}/publish_output

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
          path: ${{ github.workspace }}/publish_output
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_10EC553AA0764ED6B920A2DFC5E351DE }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_AB48DD06E7524529A359F76992D646D4 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_6FD38915B99A40A3836915894019E5F5 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'bucstop'
          slot-name: 'Production'
          package: ${{ github.workspace }}/publish_output
